mode = "optimization"

[execution]
eedf_mode = "maxwellian"
output_dir = "./output"
export_csv = false  # Set too false to disable CSV file generation

[plasma]
# These act as the initial GUESSES for the optimizer
Te_eV = 1
Tg_K = 450
pg_Pa = 1e5
R_cm = 0.05

[plasma.density]
n_e_cm3 = 1e11
n_ion_cm3 = 1e11

[plotting]
# Toggle the shaded characteristic energy block backgrounds on the Boltzmann plot
show_energy_blocks = true
mplstyle_path = "configs/crm_argon.mplstyle"

[optimization]
# Set to true to optimize both Te and ne
optimize_ne = false
Te_bounds = [0.1, 10.0]
ne_bounds = [1e10, 1e13]

[optimization.experimental_data]
# Format: "level_id" = { density = value, weight = value }