mode = "optimization"

[execution]
eedf_mode = "maxwellian"
output_dir = "./output"
export_csv = false  # Set too false to disable CSV file generation

[plasma]
# These act as the initial GUESSES for the optimizer
Te_eV = 2
Tg_K = 450
pg_Pa = 1e5
R_cm = 0.05

[plasma.density]
n_e_cm3 = 5e11
n_ion_cm3 = 5e11

[plotting]
# Toggle the shaded characteristic energy block backgrounds on the Boltzmann plot
show_energy_blocks = true
mplstyle_path = "configs/crm_argon.mplstyle"

[optimization]
# Set to true to optimize both Te and ne
optimize_ne = false
Te_bounds = [0.1, 10.0]
ne_bounds = [1e10, 1e13]

[optimization.experimental_data]
# Format: "level_id" = { density = value, weight = value }
"7" = { density = 0.02596, weight = 1 }
"8" = { density = 0.002715, weight = 1 }
"9" = { density = 0.006324, weight = 1 }
"10" = { density = 0.0004987, weight = 1 }
"11" = { density = 0.001744, weight = 1 }
